config/routes.rb
Rails.application.routes.draw do
  root             "static_pages#home"
  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup"  => "users#new"

  resources :users do
    resources :following, :followers, only: [:index]
  end

  resources :categories, only: [:show, :index] do
    resources :lessons
  end

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy, :index]
  resources :words, only: [:index, :show]

  namespace :admin do
    resources :categories, only: [:new, :edit, :create, :update]
    resources :words, only: [:new, :edit, :create, :update]
    resources :choices, only: [:create, :delete]
  end

  get "login"   => "sessions#new"
  post "login"  => "sessions#create"
  delete "logout" => "sessions#destroy"
end

app/views/shared/_activity.html.erb
<% unless user.lessons.blank? %>
  <h3><%= t "total_activity" %>(<%= user.lessons.count %>)</h3>
  <br>
  <ul class="activity">
    <% user.lessons.sort.each do |lesson| %>
      <li>
        <span class="content">
          <%= t("learned")%> <%= lesson.number_correct_choices %>/
          <%= lesson.words.count %> <%= t("word_in") %>
          <%= link_to lesson.category.title, url_for([lesson.category, lesson]) %>
        </span>
        <span class="timestamp">
          :: <%= time_ago_in_words(lesson.created_at) %> <%= t "ago"%>.
        </span>
      </li>
      <br>
    <% end %>
  </ul>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "form_contain" %> <%= pluralize @user.errors.count, "#{t("error")}" %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "form_contain" %> <%= pluralize target.errors.count, t("error") %>
    </div>
    <ul>
    <% target.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<div class="stats">
  <%= link_to user_following_index_path(user) do %>
    <strong id="following" class="stat">
      <%= user.following.count %>
    </strong>
    <%= t "following" %>
  <% end %>

  <%= link_to user_followers_path(user) do %>
    <strong id="follower" class="stat">
      <%= user.followers.count %>
    </strong>
    <%= t "followers" %>
  <% end %>
</div>